#!/bin/sh

PATH="/usr/bin:/usr/sbin"

echo_color() {
  color="$1"
  shift
  printf "\033[1;3%sm%s\033[00m\n" "$color" "$*"
}

pmount () {
	mountpoint -q "${3}" || mount -t "${1}" "${2}" "${3}" -o "${4}"
}


echo_color 3 mounting API filesystem...

pmount proc proc /proc nosuid,noexec,nodev
pmount sysfs sys /sys nosuid,noexec,nodev
pmount tmpfs run /run mode=0755,nosuid,nodev
pmount devtmpfs dev /dev mode=0755,nosuid
mkdir -p /dev/pts /dev/shm
pmount devpts devpts /dev/pts mode=0620,gid=5,nosuid,noexec
pmount tmpfs shm /dev/shm mode=1777,nosuid,nodev


echo_color 3 setting up loopback device...

ip link set up dev lo

 
echo_color 3 initializing udev...

if [ -f /usr/lib/systemd/systemd-udevd ]; then
 	/usr/lib/systemd/systemd-udevd --daemon
    /usr/bin/udevadm trigger --action=add --type=subsystems
    /usr/bin/udevadm trigger --action=add --type=devices
elif [ -f /usr/bin/udevd ]; then
	/usr/bin/udevd --daemon
	/usr/bin/udevadm trigger --action=add --type=subsystems
 	/usr/bin/udevadm trigger --action=add --type=devices
else
    busybox mdev -s
    echo /sbin/mdev > /proc/sys/kernel/hotplug
fi


echo_color 3 setting hostname...

cat > /proc/sys/kernel/hostname < /etc/hostname


echo_color 3 mounting...

mount -o remount,ro /
fsck -A -a || /bin/sh
mount -a
mount -o remount,rw /
swapon -a


echo_color 3 setting time...

export TZ=America/Los_Angeles
hwclock --systz --localtime


echo_color 3 creating special files...

install -m0664 -o root -g utmp /dev/null /var/log/wtmp
install -m0600 -o root -g utmp /dev/null /var/log/btmp
install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix


echo_color 3 logging dmesg to /var/log/dmesg.log...

dmesg > /var/log/dmesg.log


echo_color 3 loading sysctl settings...

sysctl --system


if [ -x /etc/init.d/rc.local ]; then
	echo_color 3 loading /etc/init.d/rc.local...
	(exec /etc/init.d/rc.local) &
fi


echo_color 3 starting services...

if [ -d /run/services ]; then
	rm -rf /run/services
else
	mkdir -p /run/services 
fi

cp -R /etc/init.d/services /run/services
runsvdir -P /run/services
