#!/bin/sh

UDEV="systemd"
HOSTNAME="$(cat /etc/hostname)"
PATH="/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin"

on_boot() {
    #===================
    # mount the API filesystem
    # /proc, /sys, /run, /dev, /run/lock, /dev/pts, /dev/shm
    echo_color 3 mounting API filesystem...
    mountpoint -q /proc    || mount -t proc proc /proc -o nosuid,noexec,nodev
    mountpoint -q /sys     || mount -t sysfs sys /sys -o nosuid,noexec,nodev
    mountpoint -q /run     || mount -t tmpfs run /run -o mode=0755,nosuid,nodev
    mountpoint -q /dev     || mount -t devtmpfs dev /dev -o mode=0755,nosuid
    mkdir -p /dev/pts /dev/shm
    mountpoint -q /dev/pts || mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
    mountpoint -q /dev/shm || mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev

    #===================
    # initialize system
    echo_color 3 setting up loopback device...
    /usr/sbin/ip link set up dev lo

    echo_color 3 initializing udev...
    if [ "$UDEV" = systemd ]; then
        /usr/lib/systemd/systemd-udevd --daemon
        /usr/bin/udevadm trigger --action=add --type=subsystems
        /usr/bin/udevadm trigger --action=add --type=devices
    elif [ "$UDEV" = eudev ]; then
        /usr/bin/udevd --daemon
        /usr/bin/udevadm trigger --action=add --type=subsystems
        /usr/bin/udevadm trigger --action=add --type=devices
    else # use busybox mdev as fallback:
        busybox mdev -s
        echo /sbin/mdev > /proc/sys/kernel/hotplug
    fi

    echo_color 3 setting hostname...
    echo "$HOSTNAME" >| /proc/sys/kernel/hostname

    echo_color 3 mounting...
    mount -o remount,ro /
    fsck -A -a || /bin/sh
    mount -a
    mount -o remount,rw /
    swapon -a

    echo_color 3 setting time...
    export TZ=America/Los_Angeles
    hwclock --systz --localtime

	echo_color 3 creating special files...
    install -m0664 -o root -g utmp /dev/null /var/log/wtmp
    install -m0600 -o root -g utmp /dev/null /var/log/btmp
    install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix

	echo_color 3 dmesg logged to /var/log/dmesg.log...
    dmesg > /var/log/dmesg.log

    echo_color 3 loading sysctl settings...
    sysctl --system

    if [ -x /etc/init.d/rc.local ]; then
        echo_color 3 loading /etc/init.d/rc.local...
        /etc/init.d/rc.local
    fi
}

echo_color() {
  color="$1"
  shift
  printf "\033[1;3%sm%s\033[00m\n" "$color" "$*"
}

on_boot
